Repository MTVS-Noblesse/Triplay-backend, pull requests merged in 2024-09, with the labels that each got.

#17 Feature: Domain(Clip, ClipComment, ClipCoComment, ClipReport) - contr…
  src/main/java/com/noblesse/backend/clip/controller/ClipCoCommentController.java
  src/main/java/com/noblesse/backend/clip/controller/ClipCommentController.java
  src/main/java/com/noblesse/backend/clip/controller/ClipController.java
  src/main/java/com/noblesse/backend/clip/controller/ClipReportController.java
Labels: 🔨 Refactor

#20 Feat: 로그인 기능 구현
  src/main/java/com/noblesse/backend/oauth2/config/CorsConfig.java
  src/main/java/com/noblesse/backend/oauth2/config/SecurityConfig.java
  src/main/java/com/noblesse/backend/oauth2/config/WebConfig.java
  src/main/java/com/noblesse/backend/oauth2/controller/OAuthController.java
  src/main/java/com/noblesse/backend/oauth2/entity/OAuthUser.java
  src/main/java/com/noblesse/backend/oauth2/filter/JwtFilter.java
  src/main/java/com/noblesse/backend/oauth2/filter/OAuth2Filter.java
  src/main/java/com/noblesse/backend/oauth2/repository/OAuthRepository.java
  src/main/java/com/noblesse/backend/oauth2/service/OAuth2Service.java
  src/main/java/com/noblesse/backend/oauth2/service/PrincipalOauth2UserService.java
  src/main/java/com/noblesse/backend/oauth2/util/JwtUtil.java
  src/main/resources/application.yml
Labels: ✨ Feature

#22 Feat: Post - ImageFile CRD API
  src/main/java/com/noblesse/backend/file/controller/ImageFileController.java
  src/main/java/com/noblesse/backend/file/repository/FileRepository.java
  src/main/java/com/noblesse/backend/file/service/FileService.java
Labels: ✨ Feature, 🔨 Refactor

#28 Refactor: Image File Upload 폴더 구조 정리 및 파일 이름 설정
  src/main/java/com/noblesse/backend/file/controller/ImageFileController.java
  src/main/java/com/noblesse/backend/file/entity/File.java
  src/main/java/com/noblesse/backend/file/repository/FileRepository.java
  src/main/java/com/noblesse/backend/file/service/FileService.java
  src/main/java/com/noblesse/backend/file/service/ImageFileService.java
Labels: 🔨 Refactor

#25 Feat: follow 기능 구현 & 테스트 코드 구현
  src/main/java/com/noblesse/backend/follow/Follow.java
  src/main/java/com/noblesse/backend/follow/FollowCompositeKey.java
  src/main/java/com/noblesse/backend/follow/FolloweeId.java
  src/main/java/com/noblesse/backend/follow/FollowerId.java
  src/main/java/com/noblesse/backend/follow/controller/FollowController.java
  src/main/java/com/noblesse/backend/follow/domain/Follow.java
  src/main/java/com/noblesse/backend/follow/repository/FollowRepository.java
  src/main/java/com/noblesse/backend/follow/service/FollowService.java
  src/test/java/com/noblesse/backend/follow/FollowTest.java
Labels: ✨ Feature, ✅ Test

#37 Feat: TripController 추가
  src/main/java/com/noblesse/backend/trip/controller/TripController.java
  src/main/java/com/noblesse/backend/trip/dto/FindTripResponseDTO.java
  src/main/java/com/noblesse/backend/trip/service/TripService.java
Labels: ✨ Feature

#41 Refactor: Place Entity, PostApiController
  src/main/java/com/noblesse/backend/trip/controller/PlaceApiController.java
  src/main/java/com/noblesse/backend/trip/controller/TripController.java
  src/main/java/com/noblesse/backend/trip/domain/Place.java
  src/main/java/com/noblesse/backend/trip/dto/PlaceDTO.java
  src/main/resources/application.yml
  src/test/java/com/noblesse/backend/trip/TripCRUDTests.java
Labels: 🔨 Refactor, ✅ Test

#43 Feat: 로그인 구현
  .gitignore
  build.gradle
  src/main/java/com/noblesse/backend/oauth2/config/CorsConfig.java
  src/main/java/com/noblesse/backend/oauth2/config/SecurityConfig.java
  src/main/java/com/noblesse/backend/oauth2/config/WebConfig.java
  src/main/java/com/noblesse/backend/oauth2/controller/OAuthController.java
  src/main/java/com/noblesse/backend/oauth2/dto/NaverUserInfo.java
  src/main/java/com/noblesse/backend/oauth2/dto/TokenDTO.java
  src/main/java/com/noblesse/backend/oauth2/entity/OAuthUser.java
  src/main/java/com/noblesse/backend/oauth2/filter/JwtFilter.java
  src/main/java/com/noblesse/backend/oauth2/filter/OAuth2Filter.java
  src/main/java/com/noblesse/backend/oauth2/service/OAuth2Service.java
  src/main/java/com/noblesse/backend/oauth2/util/JwtUtil.java
  src/main/resources/application.yml
Labels: ✨ Feature

#31 Feat: Post 도메인 이미지 업로드 테스트 코드 구현
  src/main/java/com/noblesse/backend/file/entity/File.java
  src/main/java/com/noblesse/backend/global/util/SwaggerConfig.java
  src/main/java/com/noblesse/backend/post/api/command/PostCoCommentCommandController.java
  src/main/java/com/noblesse/backend/post/api/command/PostCommandController.java
  src/main/java/com/noblesse/backend/post/api/command/PostCommentCommandController.java
  src/main/java/com/noblesse/backend/post/api/command/PostReportCommandController.java
  src/main/java/com/noblesse/backend/post/api/query/PostCoCommentQueryController.java
  src/main/java/com/noblesse/backend/post/api/query/PostCommentQueryController.java
  src/main/java/com/noblesse/backend/post/api/query/PostQueryController.java
  src/main/java/com/noblesse/backend/post/api/query/PostReportQueryController.java
  src/main/java/com/noblesse/backend/post/command/application/handler/CreatePostCommandHandler.java
  src/main/java/com/noblesse/backend/post/command/application/handler/DeletePostCommandHandler.java
  src/main/java/com/noblesse/backend/post/command/application/handler/UpdatePostCommandHandler.java
  src/main/java/com/noblesse/backend/post/command/application/service/PostCommandService.java
  src/main/java/com/noblesse/backend/post/command/domain/service/PostDomainService.java
  src/main/java/com/noblesse/backend/post/common/dto/PostCoCommentDTO.java
  src/main/java/com/noblesse/backend/post/common/dto/PostCommentDTO.java
  src/main/java/com/noblesse/backend/post/common/dto/PostDTO.java
  src/main/java/com/noblesse/backend/post/common/dto/PostReportDTO.java
  src/main/java/com/noblesse/backend/post/common/entity/Post.java
  src/main/java/com/noblesse/backend/post/query/application/service/PostQueryService.java
  src/test/java/com/noblesse/backend/post/PostCommandControllerTest.java
  src/test/java/com/noblesse/backend/post/PostCommandServiceTest.java
  src/test/java/com/noblesse/backend/post/PostQueryServiceTest.java
Labels: ✨ Feature, ✅ Test

#34 Feat: 취향 기능 구현 및 테스트 코드 구현
  src/main/java/com/noblesse/backend/preference/Preference.java
  src/main/java/com/noblesse/backend/preference/UserPreference.java
  src/main/java/com/noblesse/backend/preference/controller/PreferenceController.java
  src/main/java/com/noblesse/backend/preference/domain/Preference.java
  src/main/java/com/noblesse/backend/preference/domain/PreferenceInfo.java
  src/main/java/com/noblesse/backend/preference/domain/UserPreference.java
  src/main/java/com/noblesse/backend/preference/dto/NewPreferenceDTO.java
  src/main/java/com/noblesse/backend/preference/repository/PreferenceRepository.java
  src/main/java/com/noblesse/backend/preference/repository/UserPreferenceRepository.java
  src/main/java/com/noblesse/backend/preference/service/PreferenceService.java
  src/main/java/com/noblesse/backend/preference/service/PreferenceServiceImpl.java
  src/test/java/com/noblesse/backend/preference/PreferenceTest.java
Labels: ✨ Feature, ✅ Test

#44 Refactor: Trip Domain
  src/main/java/com/noblesse/backend/trip/controller/TripController.java
  src/main/java/com/noblesse/backend/trip/domain/Place.java
  src/main/java/com/noblesse/backend/trip/domain/Trip.java
  src/main/java/com/noblesse/backend/trip/domain/TripDate.java
  src/main/java/com/noblesse/backend/trip/dto/PlaceDTO.java
  src/main/java/com/noblesse/backend/trip/dto/TripDateDTO.java
  src/main/java/com/noblesse/backend/trip/dto/TripRegisterRequestDTO.java
  src/main/java/com/noblesse/backend/trip/dto/TripUpdateRequestDTO.java
  src/main/java/com/noblesse/backend/trip/service/TripService.java
  src/test/java/com/noblesse/backend/trip/TripCRUDTests.java
Labels: ✨ Feature, 🔨 Refactor

#45 [Refactor] visitdate column 수정
  src/main/java/com/noblesse/backend/trip/domain/Place.java
  src/main/java/com/noblesse/backend/trip/dto/PlaceDTO.java
  src/main/java/com/noblesse/backend/trip/service/TripService.java
  src/test/java/com/noblesse/backend/trip/TripCRUDTests.java
Labels: 🔨 Refactor

#47 Feature: Profile Image CD API
  src/main/java/com/noblesse/backend/file/controller/ImageFileController.java
  src/main/java/com/noblesse/backend/file/service/FileService.java
  src/main/java/com/noblesse/backend/file/service/ImageFileService.java
  src/main/java/com/noblesse/backend/oauth2/entity/OAuthUser.java
  src/main/java/com/noblesse/backend/post/command/application/handler/CreatePostCommandHandler.java
  src/main/java/com/noblesse/backend/post/command/application/handler/UpdatePostCommandHandler.java
Labels: ✨ Feature

#50 Refactor: Place - fix column name visit_date to visit_day
  src/main/java/com/noblesse/backend/trip/domain/Place.java
Labels: 🔨 Refactor

#35 Feat: 공지사항 기능 구현 및 테스트 코드 구현
  src/main/java/com/noblesse/backend/notice/controller/NoticeController.java
  src/main/java/com/noblesse/backend/notice/domain/Notice.java
  src/main/java/com/noblesse/backend/notice/dto/NewNoticeDTO.java
  src/main/java/com/noblesse/backend/notice/repository/NoticeRepository.java
  src/main/java/com/noblesse/backend/notice/service/NoticeService.java
  src/main/java/com/noblesse/backend/notice/service/NoticeServiceImpl.java
  src/test/java/com/noblesse/backend/notice/NoticeTest.java
Labels: ✨ Feature, ✅ Test

#51 Feat: 장소 정보 얻어오는 api 컨트롤러, 서비스 구현
  src/main/java/com/noblesse/backend/trip/controller/PlaceApiController.java
  src/main/java/com/noblesse/backend/trip/service/PlaceService.java
Labels: ✨ Feature

#52 [Feat] User 정보 조회 기능 추가
  src/main/java/com/noblesse/backend/file/controller/ImageFileController.java
  src/main/java/com/noblesse/backend/file/service/FileService.java
  src/main/java/com/noblesse/backend/file/service/ImageFileService.java
  src/main/java/com/noblesse/backend/oauth2/controller/OAuthController.java
  src/main/java/com/noblesse/backend/oauth2/dto/UserDTO.java
  src/main/java/com/noblesse/backend/oauth2/util/JwtUtil.java
  src/main/java/com/noblesse/backend/post/query/application/service/PostQueryService.java
  src/main/java/com/noblesse/backend/trip/dto/TripDTO.java
  src/main/java/com/noblesse/backend/trip/service/TripService.java
  src/test/java/com/noblesse/backend/trip/TripCRUDTests.java
Labels: ✨ Feature, 🔨 Refactor

#55 Refactor: clip 상세 조회 endpoint 수정
  src/main/java/com/noblesse/backend/clip/controller/ClipController.java
Labels: 🔨 Refactor

#56 Refactor: Fix Trip Entity
  src/main/java/com/noblesse/backend/trip/domain/Place.java
  src/main/java/com/noblesse/backend/trip/dto/PlaceDTO.java
  src/main/java/com/noblesse/backend/trip/service/TripService.java
  src/test/java/com/noblesse/backend/trip/TripCRUDTests.java
Labels: 🔨 Refactor

#53 Feat: 팔로우 기능 수정
  src/main/java/com/noblesse/backend/follow/controller/FollowController.java
  src/main/java/com/noblesse/backend/follow/repository/FollowRepository.java
  src/main/java/com/noblesse/backend/follow/service/FollowService.java
  src/test/java/com/noblesse/backend/follow/FollowTest.java
Labels: ✨ Feature

#57 Refactor: Fix Place Entity
  src/main/java/com/noblesse/backend/trip/domain/Place.java
Labels: 🔨 Refactor

#59 Refactor: File Entity 수정, PostImageUpload 관련 로직 수정
  src/main/java/com/noblesse/backend/file/controller/ImageFileController.java
  src/main/java/com/noblesse/backend/file/entity/File.java
  src/main/java/com/noblesse/backend/file/service/FileService.java
  src/main/java/com/noblesse/backend/file/service/ImageFileService.java
  src/main/java/com/noblesse/backend/post/api/command/PostCommandController.java
  src/main/java/com/noblesse/backend/post/command/application/handler/CreatePostCommandHandler.java
  src/main/java/com/noblesse/backend/post/command/application/handler/UpdatePostCommandHandler.java
  src/main/java/com/noblesse/backend/post/common/dto/PostDTO.java
Labels: 🔨 Refactor

#61 Refactor: 이미지 파일 링크 조회 API 수정
  src/main/java/com/noblesse/backend/file/entity/File.java
  src/main/java/com/noblesse/backend/file/service/FileService.java
Labels: 🔨 Refactor
