Repository MTVS-Noblesse/Triplay-backend, pull requests merged in 2024-11, with the labels that each got.

#76 Feat: 클립 관리 도메인 기능 구현 완료 #71
  build.gradle
  src/main/java/com/noblesse/backend/clip/controller/ClipController.java
  src/main/java/com/noblesse/backend/clip/controller/ClipReportController.java
  src/main/java/com/noblesse/backend/clip/domain/Clip.java
  src/main/java/com/noblesse/backend/clip/domain/ClipReport.java
  src/main/java/com/noblesse/backend/clip/dto/ClipRegistRequestDTO.java
  src/main/java/com/noblesse/backend/clip/repository/ClipReportRepository.java
  src/main/java/com/noblesse/backend/clip/service/ClipReportService.java
  src/main/java/com/noblesse/backend/clip/service/ClipService.java
  src/main/java/com/noblesse/backend/file/service/FileService.java
  src/main/java/com/noblesse/backend/global/handler/GlobalExceptionHandler.java
  src/main/java/com/noblesse/backend/manage/clip/controller/ClipManagementController.java
  src/main/java/com/noblesse/backend/manage/clip/dto/ReportedClipDTO.java
  src/main/java/com/noblesse/backend/manage/clip/dto/ReportedClipDetailDTO.java
  src/main/java/com/noblesse/backend/manage/clip/service/ClipManagementService.java
  src/main/resources/application.yml
  src/test/java/com/noblesse/backend/clip/ClipCRUDTests.java
  src/test/java/com/noblesse/backend/manage/clip/ClipManagementTest.java
Labels: ✨ Feature

#77 Refactor-Post 조회 기능 수정(전체, 일부)
  .gitignore
  build.gradle
  src/main/java/com/noblesse/backend/common/config/QuerydslConfig.java
  src/main/java/com/noblesse/backend/common/converter/StringListConverter.java
  src/main/java/com/noblesse/backend/file/dto/FileDTO.java
  src/main/java/com/noblesse/backend/file/service/ImageFileService.java
  src/main/java/com/noblesse/backend/post/common/dto/PostDTO.java
  src/main/java/com/noblesse/backend/post/query/application/service/PostQueryService.java
  src/main/java/com/noblesse/backend/post/query/infrastructure/persistence/repository/CustomPostRepository.java
  src/main/java/com/noblesse/backend/post/query/infrastructure/persistence/repository/CustomPostRepositoryImpl.java
  src/main/java/com/noblesse/backend/post/query/infrastructure/persistence/repository/PostRepository.java
  src/main/java/com/noblesse/backend/trip/domain/Place.java
Labels: ✨ Feature, 🔨 Refactor, ⚙️ Setting

#83 Feat: follow 기능 프론트 연동
  src/main/java/com/noblesse/backend/follow/controller/FollowController.java
  src/main/java/com/noblesse/backend/follow/repository/FollowRepository.java
  src/main/java/com/noblesse/backend/follow/service/FollowService.java
  src/test/java/com/noblesse/backend/follow/FollowTest.java
Labels: ✨ Feature

#86 feat: Clip 썸네일 이미지 불러오기 기능 추가 구현
  src/main/java/com/noblesse/backend/clip/service/ClipService.java
  src/main/java/com/noblesse/backend/file/controller/ImageFileController.java
  src/main/java/com/noblesse/backend/file/service/FileService.java
Labels: ✨ Feature

#84 [Feat] 프로필 사진 삭제 로직 수정
  build.gradle
  src/main/java/com/noblesse/backend/file/controller/ImageFileController.java
  src/main/java/com/noblesse/backend/file/service/FileService.java
  src/main/java/com/noblesse/backend/oauth2/controller/OAuthController.java
  src/main/java/com/noblesse/backend/oauth2/dto/UserDTO.java
  src/main/java/com/noblesse/backend/oauth2/security/PrincipalDetails.java
  src/main/java/com/noblesse/backend/oauth2/util/JwtUtil.java
Labels: ✨ Feature, 🔨 Refactor

#87 [Feat] 본인이 작성한 여행 계획, 포스트, 클립 조회 기능 추가
  src/main/java/com/noblesse/backend/BaseTimeEntity.java
  src/main/java/com/noblesse/backend/clip/controller/ClipController.java
  src/main/java/com/noblesse/backend/clip/repository/ClipRepository.java
  src/main/java/com/noblesse/backend/clip/service/ClipService.java
  src/main/java/com/noblesse/backend/post/api/query/PostQueryController.java
  src/main/java/com/noblesse/backend/post/query/application/service/PostQueryService.java
  src/main/java/com/noblesse/backend/trip/controller/TripController.java
  src/main/java/com/noblesse/backend/trip/domain/Trip.java
  src/main/java/com/noblesse/backend/trip/repository/TripRepository.java
  src/main/java/com/noblesse/backend/trip/service/TripService.java
Labels: ✨ Feature, 🔨 Refactor

#88 [Fix] 기존 가지고 있던 오류 해결
  src/main/java/com/noblesse/backend/clip/service/ClipService.java
  src/main/java/com/noblesse/backend/post/query/application/service/PostQueryService.java
Labels: ✨ Feature

#92 Feat: 프로메테우스 및 그라파나 모니터링 시스템 구현 완료
  .gitignore
  build.gradle
  docker-compose.yml
  grafana.ini
  prometheus.yml
  src/main/java/com/noblesse/backend/common/annotation/LogExecutionTime.java
  src/main/java/com/noblesse/backend/common/aop/LogAspect.java
  src/main/java/com/noblesse/backend/common/aop/LogCleanupScheduler.java
  src/main/java/com/noblesse/backend/common/config/LogDatabaseConfig.java
  src/main/java/com/noblesse/backend/common/controller/LogAnalyticsController.java
  src/main/java/com/noblesse/backend/common/controller/LogController.java
  src/main/java/com/noblesse/backend/common/dto/LogDTO.java
  src/main/java/com/noblesse/backend/common/entity/LogEntity.java
  src/main/java/com/noblesse/backend/common/repository/LogRepository.java
  src/main/java/com/noblesse/backend/common/service/LogService.java
  src/main/java/com/noblesse/backend/config/MainDatabaseConfig.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
  web-config.yml
Labels: ✨ Feature

#93 [Refactor] 게시물 조회 기능 개선
  src/main/java/com/noblesse/backend/file/controller/ImageFileController.java
  src/main/java/com/noblesse/backend/file/dto/FileDTO.java
  src/main/java/com/noblesse/backend/file/service/FileService.java
  src/main/java/com/noblesse/backend/file/service/ImageFileService.java
  src/main/java/com/noblesse/backend/oauth2/controller/OAuthController.java
  src/main/java/com/noblesse/backend/oauth2/dto/UserDTO.java
  src/main/java/com/noblesse/backend/oauth2/service/OAuth2Service.java
  src/main/java/com/noblesse/backend/oauth2/util/JwtUtil.java
  src/main/java/com/noblesse/backend/post/api/command/PostCommentCommandController.java
  src/main/java/com/noblesse/backend/post/command/application/handler/DeletePostCommentCommandHandler.java
  src/main/java/com/noblesse/backend/post/common/dto/PostCommentDTO.java
  src/main/java/com/noblesse/backend/post/common/dto/PostDTO.java
  src/main/java/com/noblesse/backend/post/query/application/service/PostQueryService.java
  src/main/java/com/noblesse/backend/post/query/infrastructure/persistence/repository/CustomPostRepository.java
  src/main/java/com/noblesse/backend/post/query/infrastructure/persistence/repository/CustomPostRepositoryImpl.java
  src/main/java/com/noblesse/backend/post/query/infrastructure/persistence/repository/PostCommentRepository.java
  src/main/java/com/noblesse/backend/post/query/infrastructure/persistence/repository/PostRepository.java
  src/main/java/com/noblesse/backend/post/query/mapper/PostMapper.java
  src/main/java/com/noblesse/backend/preference/controller/PreferenceController.java
  src/main/java/com/noblesse/backend/preference/service/PreferenceServiceImpl.java
  src/main/java/com/noblesse/backend/trip/dto/PlaceDTO.java
  src/main/resources/application.yml
  src/main/resources/mapper/PostMapper.xml
Labels: 🔨 Refactor

#94 [Feat] 취향 등록, 수정 기능 구현
  src/main/java/com/noblesse/backend/file/controller/ImageFileController.java
  src/main/java/com/noblesse/backend/file/service/FileService.java
  src/main/java/com/noblesse/backend/post/query/application/service/PostQueryService.java
  src/main/java/com/noblesse/backend/post/query/mapper/PostMapper.java
  src/main/java/com/noblesse/backend/trip/dto/TripDTO.java
  src/main/resources/mapper/PostMapper.xml
Labels: 🔨 Refactor
